name:                wth
version:             0.1.0.0
github:              "ivan-ristovic/wth"
license:             GPL3
author:              "Ana Bajic, Ivan Ristovic, Strahinja Stanojevic"
maintainer:          "ivan_ristovic@math.rs"
copyright:           "2019 Ana Bajic, Ivan Ristovic, Strahinja Stanojevic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ivan_ristovic/wth>

dependencies:
- base >= 4.7 && < 5
- gloss
- gloss-juicy
- bytestring
- JuicyPixels
- curl
- download-curl

library:
  source-dirs: src

executables:
  wth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wth

tests:
  wth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wth
